### ISSUE TITLE
cannot create tablespace, no datafile

### ISSUE THREAD

**Issue by mfominov** [Nosmoht/ansible-library-oracle#3]
failed: [127.0.0.1] => (item={'value': {u'next_size': u'0', u'autoextend': False, u'name': u'UFS_TABLE', u'max_size': u'0', u'size': u'30g'}, 'key': u'tables'}) => {"failed": true, "item": {"key": "tables", "value": {"autoextend": false, "max_size": "0", "name": "UFS_TABLE", "next_size": "0", "size": "30g"}}, "msg": "CREATE TABLESPACE UFS_TABLE DATAFILE SIZE 30g AUTOEXTEND OFF BLOCKSIZE 8k: ORA-02236: invalid file name\n"}
failed: [127.0.0.1] => (item={'value': {u'next_size': u'16M', u'autoextend': False, u'name': u'UFS_INDEX', u'max_size': u'30G', u'size': u'5g'}, 'key': u'index'}) => {"failed": true, "item": {"key": "index", "value": {"autoextend": false, "max_size": "30G", "name": "UFS_INDEX", "next_size": "16M", "size": "5g"}}, "msg": "CREATE TABLESPACE UFS_INDEX DATAFILE SIZE 5g AUTOEXTEND OFF BLOCKSIZE 8k: ORA-02236: invalid file name\n"}

**Comment by Nosmoht** [comment]
Sorry, for answering that late.

The current module assumes that system parameter DB_CREATE_FILE_DEST is used. It seems that this parameter is not set in your DB.

If needed, we can add support for static filenames to the module. Just let me know.

**Comment by Nosmoht** [comment]
@mfominov any feedback? Did you try it with DB_CREATE_FILE_DEST set?

**Comment by mfominov** [comment]
@Nosmoht sorry for so my slow answer, now i can't test that so just closing. Im not so good in oracle. thx for feed back
